/**
 * Season allocation.
 *
 * Admins define standing blocks ("Boys Basketball, Rakoczy Full Court, Mon-Fri
 * 3:30-5:30 PM, Nov 10 - Mar 6"), the system expands them, shows every
 * collision, and refuses to publish until each one is resolved. Publishing then
 * writes real bookings, which means the exclusion constraint is the final
 * arbiter -- the collision screen is a courtesy, not the enforcement.
 */

import { ActivityType, BookingStatus, TeamLevel, type StandingBlock } from "@prisma/client";
import { prisma } from "@/lib/db";
import { NotFoundError, ValidationError } from "@/lib/errors";
import { recordAudit } from "@/lib/audit";
import { dateColumnToISO } from "@/lib/time";
import { expandRecurrence } from "@/domain/recurrence";
import {
  detectCollisions,
  type AllocationOccurrence,
  type CollisionReport,
  type ExistingReservation,
} from "@/domain/allocation";
import { indexSubSpaces, type SubSpaceNode } from "@/domain/conflict-graph";
import { computePriority } from "@/domain/priority";
import { selectRule } from "@/domain/rules-engine";
import { createBooking, type Actor } from "./booking-service";

export interface AllocationPreview {
  report: CollisionReport;
  occurrences: AllocationOccurrence[];
  seasonName: string;
}

/**
 * Expand every unpublished standing block in a season and report collisions,
 * both against each other and against bookings already on the calendar.
 */
export async function previewSeasonAllocation(seasonId: string): Promise<AllocationPreview> {
  const season = await prisma.season.findUnique({
    where: { id: seasonId },
    include: {
      standingBlocks: {
        include: { sport: true, subSpace: { include: { facility: true } } },
      },
    },
  });
  if (!season) throw new NotFoundError("Season");

  const fromDate = dateColumnToISO(season.startDate);
  const toDate = dateColumnToISO(season.endDate);

  const occurrences: AllocationOccurrence[] = [];

  for (const block of season.standingBlocks) {
    const expanded = expandRecurrence({
      rrule: block.rrule,
      startTime: block.startTime,
      endTime: block.endTime,
      fromDate,
      toDate,
    });

    for (const occ of expanded) {
      occurrences.push({
        blockId: block.id,
        blockLabel: `${block.sport.name} ${block.teamLevel} — ${block.subSpace.name} ${block.startTime}-${block.endTime}`,
        sportName: block.sport.name,
        teamLevel: block.teamLevel,
        subSpaceId: block.subSpaceId,
        subSpaceName: `${block.subSpace.facility.name} — ${block.subSpace.name}`,
        priority: block.priority,
        date: occ.date,
        startAt: occ.startAt,
        endAt: occ.endAt,
      });
    }
  }

  // Anything already holding a slot in the season window.
  const existingRows = await prisma.booking.findMany({
    where: {
      startAt: { lt: season.endDate },
      endAt: { gt: season.startDate },
      status: {
        in: [
          BookingStatus.PENDING_APPROVAL,
          BookingStatus.APPROVED,
          BookingStatus.AWAITING_DOCUMENTS,
          BookingStatus.AWAITING_PAYMENT,
          BookingStatus.CONFIRMED,
          BookingStatus.CHECKED_IN,
        ],
      },
      // Bookings generated by this season's own blocks are not collisions.
      standingBlock: { is: null },
    },
    include: { subSpace: { include: { facility: true } } },
  });

  const existing: ExistingReservation[] = existingRows.map((b) => ({
    bookingId: b.id,
    reference: b.reference,
    title: b.title,
    subSpaceId: b.subSpaceId,
    subSpaceName: `${b.subSpace.facility.name} — ${b.subSpace.name}`,
    priority: b.priority,
    startAt: b.startAt,
    endAt: b.endAt,
  }));

  const allSubSpaces = await prisma.subSpace.findMany({ where: { active: true } });
  const report = detectCollisions(
    occurrences,
    existing,
    indexSubSpaces(allSubSpaces as SubSpaceNode[]),
  );

  return { report, occurrences, seasonName: season.name };
}

export interface PublishResult {
  created: number;
  skipped: { date: string; blockLabel: string; reason: string }[];
  seasonId: string;
}

/**
 * Publish a season's allocation: turn every occurrence into a real booking.
 *
 * Refuses to run while collisions remain. Acceptance criterion 6.
 */
export async function publishSeasonAllocation(
  seasonId: string,
  actor: Actor,
  options: { force?: boolean } = {},
): Promise<PublishResult> {
  const preview = await previewSeasonAllocation(seasonId);

  if (!preview.report.publishable && !options.force) {
    throw new ValidationError(
      `${preview.report.collisions.length} unresolved collision(s) remain. ` +
        "Resolve every collision before publishing.",
      { collisions: preview.report.collisions.slice(0, 20) },
    );
  }

  const season = await prisma.season.findUnique({
    where: { id: seasonId },
    include: { standingBlocks: { include: { createdBy: true, sport: true } } },
  });
  if (!season) throw new NotFoundError("Season");

  const blocksById = new Map(season.standingBlocks.map((b) => [b.id, b]));
  const skipped: PublishResult["skipped"] = [];
  let created = 0;

  for (const occ of preview.occurrences) {
    const block = blocksById.get(occ.blockId);
    if (!block) continue;

    try {
      await createBooking(
        {
          requesterId: block.createdById,
          subSpaceId: occ.subSpaceId,
          activityType: ActivityType.TEAM_PRACTICE,
          title: `${block.sport.name} ${humanTeamLevel(block.teamLevel)} practice`,
          startAt: occ.startAt,
          endAt: occ.endAt,
          sportId: block.sportId,
          teamLevel: block.teamLevel,
          seasonId,
          standingBlockId: block.id,
          overrideAvailability: true,
        },
        actor,
      );
      created += 1;
    } catch (error) {
      // A single bad day (a holiday blackout, a lingering conflict) must not
      // abort the whole season.
      skipped.push({
        date: occ.date,
        blockLabel: occ.blockLabel,
        reason: error instanceof Error ? error.message : String(error),
      });
    }
  }

  await prisma.standingBlock.updateMany({
    where: { seasonId },
    data: { published: true },
  });
  await prisma.season.update({ where: { id: seasonId }, data: { published: true } });

  await recordAudit({
    entityType: "season",
    entityId: seasonId,
    action: "season.published",
    actorId: actor.id,
    actorLabel: actor.name,
    ipAddress: actor.ipAddress,
    payload: {
      created,
      skipped: skipped.length,
      forced: options.force ?? false,
      occurrences: preview.occurrences.length,
    },
  });

  return { created, skipped, seasonId };
}

export interface StandingBlockInput {
  seasonId: string;
  sportId: string;
  subSpaceId: string;
  teamLevel: TeamLevel;
  rrule: string;
  startTime: string;
  endTime: string;
  createdById: string;
}

export async function createStandingBlock(
  input: StandingBlockInput,
  actor: Actor,
): Promise<StandingBlock> {
  const rules = await prisma.rule.findMany();
  const { rule } = selectRule(rules, ActivityType.TEAM_PRACTICE, "HEAD_COACH");
  const priority = computePriority(rule, input.teamLevel);

  const block = await prisma.standingBlock.create({
    data: { ...input, priority },
  });

  await recordAudit({
    entityType: "standing_block",
    entityId: block.id,
    action: "standing_block.created",
    actorId: actor.id,
    actorLabel: actor.name,
    payload: {
      seasonId: input.seasonId,
      rrule: input.rrule,
      window: `${input.startTime}-${input.endTime}`,
      priority,
    },
  });

  return block;
}

export async function deleteStandingBlock(blockId: string, actor: Actor): Promise<void> {
  const block = await prisma.standingBlock.findUnique({ where: { id: blockId } });
  if (!block) throw new NotFoundError("Standing block");
  if (block.published) {
    throw new ValidationError(
      "That block is published. Cancel its bookings individually, or unpublish the season first.",
    );
  }

  await prisma.standingBlock.delete({ where: { id: blockId } });
  await recordAudit({
    entityType: "standing_block",
    entityId: blockId,
    action: "standing_block.deleted",
    actorId: actor.id,
    actorLabel: actor.name,
  });
}

function humanTeamLevel(level: TeamLevel): string {
  switch (level) {
    case TeamLevel.VARSITY:
      return "varsity";
    case TeamLevel.JV:
      return "JV";
    case TeamLevel.FRESHMAN:
      return "freshman";
    case TeamLevel.MIDDLE_SCHOOL:
      return "middle school";
    default:
      return "";
  }
}
