export const SAFETY_CATEGORIES = [
  "profanity_text",
  "profanity_speech",
  "sexual_or_obscene_language",
  "threatening_language",
  "harassment_or_slur",
  "student_id_badge",
  "name_on_document",
  "class_schedule",
  "email_address",
  "phone_number",
  "postal_address",
  "birth_date",
  "possible_medical_private_information",
  "license_plate",
  "sensitive_device_screen",
  "nudity_or_sexual_content",
  "violence",
  "weapon",
  "drugs",
  "alcohol",
  "vaping_or_smoking",
  "obscene_gesture",
  "inappropriate_activity",
  "identifiable_person",
] as const;

export type SafetyCategory = (typeof SAFETY_CATEGORIES)[number];

export const SAFETY_CATEGORY_LABELS: Record<SafetyCategory, string> = {
  profanity_text: "Profanity in visible text",
  profanity_speech: "Profanity in speech",
  sexual_or_obscene_language: "Sexual or obscene language",
  threatening_language: "Threatening language",
  harassment_or_slur: "Harassment or discriminatory slur",
  student_id_badge: "Student ID or badge visible",
  name_on_document: "Name visible on paperwork",
  class_schedule: "Class schedule visible",
  email_address: "Email address visible or spoken",
  phone_number: "Phone number visible or spoken",
  postal_address: "Address visible or spoken",
  birth_date: "Birth date visible or spoken",
  possible_medical_private_information: "Possible medical or private information",
  license_plate: "License plate visible",
  sensitive_device_screen: "Sensitive device screen visible",
  nudity_or_sexual_content: "Nudity or sexual content",
  violence: "Violence",
  weapon: "Weapon",
  drugs: "Drugs",
  alcohol: "Alcohol",
  vaping_or_smoking: "Vaping or smoking",
  obscene_gesture: "Obscene gesture",
  inappropriate_activity: "Inappropriate activity",
  identifiable_person: "Identifiable person",
};
